### ISSUE TITLE
Add .sav file uploader and parser to get current inventory progress

### ISSUE THREAD

**Issue by Fleckeri** [BobertForever/drg-completionist#5]
Allow users to upload their `{id}_player.sav` file located at `C:\Program Files (x86)\Steam\steamapps\common\Deep Rock Galactic\FSD\Saved\SaveGames` to get their current inventory status without having to manually enter it themselves.

**Comment by BobertForever** [comment]
Added in https://github.com/BobertForever/drg-completionist/commit/b298b6a3ade691a80d6d4bbc9ec833b866c19643
